### ISSUE TITLE
rename warnings.json

### ISSUE THREAD

**Issue by NvBgm** [waynedgrant/meteo-alarm-weather-warnings#2]
Why must i rename warnings.json to warnings.php ??
There is already a file named warnings.php
Must i delete thid existing  file ????

**Comment by Flyingfufu** [comment]
Hi,

The one existing is **W**arnings.php . Don't touch it ! Simply rename **w**arnings.**json** to warnings.**php** and all will work fine.

**Comment by NvBgm** [comment]
Thanks I got it running ...

**Comment by waynedgrant** [comment]
Thanks @Flyingfufu
