### ISSUE TITLE
HTTP error 500 

### ISSUE THREAD

**Issue by NvBgm** [waynedgrant/meteo-alarm-weather-warnings#3]
Afther a clean instal of my raspberry i also did a clean instal of the Meteo-wheather-warnings.
All went well til i would test it.

/warnings.json

{
    "error": "GET parameter country is required"
}

Oke this is correct because it needs the country variable

/warnings.json?country=UK

![image](https://user-images.githubusercontent.com/8125819/73833227-ec06de00-4809-11ea-8cf2-8899a952947d.png)

Error 500

Please help...

**Comment by waynedgrant** [comment]
Check and see if there are any further details in the logs of your web server.

**Comment by NvBgm** [comment]
Hello om,

I did not see anything in the logs that indicate me to a error ore mistake.
I think it is not the PHP or apache that give me this error

When i put the adres in mij browser like this:

http://192.168.2.27/meteoalarm/warnings.php?country=NL&region=017&time_zone=Europe/Amsterdam

Then it give me : 

{
"error": "Response code 502 returned by http://meteoalarm.eu/documents/rss/nl/NL017.rss"
}

When i try to get the rrs feed in my browser:

http://meteoalarm.eu/documents/rss/nl/NL017.rss

It take's about 20 sec before i get the info or a get a ERR_CONNECTION_TIMED_OUT

So i don't know what this can be but it is notting to do with the php scripts i think.

**Comment by NvBgm** [comment]
This error i find in the apachelog file

[Thu Feb 13 21:52:51.409824 2020] [php7:error] [pid 468] [client 192.168.2.50:51395] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/meteoalarm/warnings.php:29\nStack trace:\n#0 {main}\n  thrown in /var/www/html/meteoalarm/warnings.php on line 29

**Comment by NvBgm** [comment]
I did solve this problem 
Had to instal 👍 

sudo apt-get install php7.x-xml

Restart apache and eureka....

**Comment by waynedgrant** [comment]
Good to hear @NvBgm
