### ISSUE TITLE
End of meteoalarm.

### ISSUE THREAD

**Issue by conligwx** [waynedgrant/meteo-alarm-weather-warnings#5]
Just informing you met office has stopped feeding meteoalarm.eu a few weeks back you will not get ANY alarms.

more info here:  https://cumulus.hosiene.co.uk/viewtopic.php?f=14&t=18948

not sure if you want to take a feed from the met office rss feed instead, but the meteoalarm v2 website is far from/ready.

https://www.metoffice.gov.uk/weather/guides/rss

**Comment by waynedgrant** [comment]
Thanks. I'd noticed UK alerts had stopped on my own weather site but hadn't had time to follow it up.

I may look to spin up a met office focussed rss equivalent but no promises.

**Comment by palsoft333** [comment]
Meteoalarm v2 is up and ready.
Any chance you will implement the new feed URLs?

They should be documented here as far as I understand:
https://edrop.zamg.ac.at/owncloud/index.php/s/KLnQATfay8FAREQ#pdfviewer

**Comment by waynedgrant** [comment]
I'm deprecating all my repos to focus on other projects :(
